//! Property-based tests for Baby Jubjub FROST implementation.

use crate::*;
use alloc::collections::BTreeMap;
use alloc::format;
use alloc::vec;
use alloc::vec::Vec;
use core::ops::{Add, Neg};
use proptest::prelude::*;
use rand_core::OsRng;

proptest! {
    #[test]
    fn test_scalar_arithmetic_properties(a in any::<[u8; 32]>(), b in any::<[u8; 32]>()) {
        let scalar_a = BabyJubjubScalar::from_bytes_mod_order_wide(&a);
        let scalar_b = BabyJubjubScalar::from_bytes_mod_order_wide(&b);

        // Test commutativity of addition
        let sum1 = scalar_a.add(scalar_b);
        let sum2 = scalar_b.add(scalar_a);
        assert_eq!(sum1, sum2);

        // Test associativity of addition
        let scalar_c = BabyJubjubScalar::random(&mut OsRng);
        let sum_ab_c = sum1.add(scalar_c);
        let sum_a_bc = scalar_a.add(scalar_b.add(scalar_c));
        assert_eq!(sum_ab_c, sum_a_bc);

        // Test identity element
        let zero = BabyJubjubScalar::zero();
        assert_eq!(scalar_a.add(zero), scalar_a);
        assert_eq!(zero.add(scalar_a), scalar_a);

        // Test inverse
        let neg_a = scalar_a.neg();
        assert_eq!(scalar_a.add(neg_a), zero);
    }

    #[test]
    fn test_point_arithmetic_properties(scalar_a in any::<[u8; 32]>(), scalar_b in any::<[u8; 32]>()) {
        let scalar_a = BabyJubjubScalar::from_bytes_mod_order_wide(&scalar_a);
        let scalar_b = BabyJubjubScalar::from_bytes_mod_order_wide(&scalar_b);
        let generator = BabyJubjubPoint::generator();

        // Test scalar multiplication properties
        let point_a = generator.mul(&scalar_a);
        let point_b = generator.mul(&scalar_b);

        // Test distributive property: (a + b) * G = a * G + b * G
        let sum_scalars = scalar_a.add(scalar_b);
        let point_sum = generator.mul(&sum_scalars);
        let sum_points = point_a.add(point_b);
        assert_eq!(point_sum, sum_points);

        // Test associativity: (a * b) * G = a * (b * G)
        let product_scalars = scalar_a.mul(&scalar_b);
        let point_product = generator.mul(&product_scalars);
        let point_b_scaled = point_b.mul(&scalar_a);
        assert_eq!(point_product, point_b_scaled);

        // Test identity element
        let identity = BabyJubjubPoint::identity();
        let zero_scalar = BabyJubjubScalar::zero();
        assert_eq!(generator.mul(&zero_scalar), identity);
        assert_eq!(point_a.add(identity), point_a);
        assert_eq!(identity.add(point_a), point_a);
    }

    #[test]
    fn test_field_arithmetic_properties(a in any::<[u8; 32]>(), b in any::<[u8; 32]>()) {
        let field_a = BabyJubjubField::from_bytes(&a).unwrap_or(BabyJubjubField::zero());
        let field_b = BabyJubjubField::from_bytes(&b).unwrap_or(BabyJubjubField::zero());

        // Test commutativity of addition
        let sum1 = field_a.add(field_b);
        let sum2 = field_b.add(field_a);
        assert_eq!(sum1, sum2);

        // Test associativity of addition
        let field_c = BabyJubjubField::random(&mut OsRng);
        let sum_ab_c = sum1.add(field_c);
        let sum_a_bc = field_a.add(field_b.add(field_c));
        assert_eq!(sum_ab_c, sum_a_bc);

        // Test identity element
        let zero = BabyJubjubField::zero();
        assert_eq!(field_a.add(zero), field_a);
        assert_eq!(zero.add(field_a), field_a);

        // Test inverse
        let neg_a = field_a.neg();
        assert_eq!(field_a.add(neg_a), zero);
    }

    #[test]
    fn test_serialization_roundtrip(scalar_bytes in any::<[u8; 32]>()) {
        // Test scalar serialization roundtrip
        if let Some(scalar) = BabyJubjubScalar::from_bytes(&scalar_bytes) {
            let serialized = scalar.to_bytes();
            let deserialized = BabyJubjubScalar::from_bytes(&serialized).unwrap();
            assert_eq!(scalar, deserialized);
        }

        // Test field serialization roundtrip
        if let Some(field) = BabyJubjubField::from_bytes(&scalar_bytes) {
            let serialized = field.to_bytes();
            let deserialized = BabyJubjubField::from_bytes(&serialized).unwrap();
            assert_eq!(field, deserialized);
        }
    }

    #[test]
    fn test_point_on_curve_property(scalar_bytes in any::<[u8; 32]>()) {
        let scalar = BabyJubjubScalar::from_bytes_mod_order_wide(&scalar_bytes);
        let generator = BabyJubjubPoint::generator();
        let point = generator.mul(&scalar);

        // All points generated by scalar multiplication should be on the curve
        assert!(point.is_on_curve());

        // Identity point should be on the curve
        let identity = BabyJubjubPoint::identity();
        assert!(identity.is_on_curve());
    }

    #[test]
    fn test_hash_function_properties(message in any::<Vec<u8>>()) {
        // Test that hash functions produce consistent output
        // let message = b"test_hash_function_properties";
        let h1_1 = BabyJubjubSha256::H1(&message);
        let h1_2 = BabyJubjubSha256::H1(&message);
        assert_eq!(h1_1, h1_2);

        let h2_1 = BabyJubjubSha256::H2(&message);
        let h2_2 = BabyJubjubSha256::H2(&message);
        assert_eq!(h2_1, h2_2);

        let h3_1 = BabyJubjubSha256::H3(&message);
        let h3_2 = BabyJubjubSha256::H3(&message);
        assert_eq!(h3_1, h3_2);

        let h4_1 = BabyJubjubSha256::H4(&message);
        let h4_2 = BabyJubjubSha256::H4(&message);
        assert_eq!(h4_1, h4_2);

        let h5_1 = BabyJubjubSha256::H5(&message);
        let h5_2 = BabyJubjubSha256::H5(&message);
        assert_eq!(h5_1, h5_2);

        // Test that different messages produce different hashes
        let message0 = vec![0u8; 32];
        let message1 = vec![1u8; 32];
        let h1_diff = BabyJubjubSha256::H1(&message0);
        let h1_diff2 = BabyJubjubSha256::H1(&message1);
        assert_ne!(h1_diff, h1_diff2);
    }

    #[test]
    fn test_frost_signing_properties(
        max_signers in 2..6u16,
        min_signers in 2..6u16,
        message in any::<Vec<u8>>()
    ) {
        prop_assume!(min_signers <= max_signers);
        prop_assume!(max_signers >= 2);

        let mut rng = OsRng;

        // Generate key shares
        let (shares, pubkeys) = keys::generate_with_dealer(
            max_signers,
            min_signers,
            keys::IdentifierList::Default,
            &mut rng,
        ).unwrap();

        // Create key packages
        let mut key_packages = BTreeMap::new();
        for (identifier, secret_share) in &shares {
            let key_package = keys::KeyPackage::try_from(secret_share.clone()).unwrap();
            key_packages.insert(*identifier, key_package);
        }

        // Round 1: Generate nonces and commitments
        let mut nonces = BTreeMap::new();
        let mut commitments = BTreeMap::new();

        for (identifier, key_package) in &key_packages {
            let (nonce, commitment) = round1::commit(key_package.signing_share(), &mut rng);
            nonces.insert(*identifier, nonce);
            commitments.insert(*identifier, commitment);
        }

        // Create signing package
        let signing_package = SigningPackage::new(commitments, &message);

        // Round 2: Generate signature shares
        let mut signature_shares = BTreeMap::new();

        for (identifier, key_package) in &key_packages {
            let signature_share = round2::sign(
                &signing_package,
                &nonces[identifier],
                key_package,
            ).unwrap();
            signature_shares.insert(*identifier, signature_share);
        }

        // Aggregate signature
        let signature = aggregate(&signing_package, &signature_shares, &pubkeys).unwrap();

        // Verify signature
        let is_valid = pubkeys.verifying_key().verify(&message, &signature);
        assert!(is_valid.is_ok());

        // Test that signature is invalid for different message
        let different_message = vec![0u8; message.len()];
        let is_invalid = pubkeys.verifying_key().verify(&different_message, &signature);
        assert!(is_invalid.is_err());
    }
}

// Additional property-based tests for edge cases
// TODO: Fix proptest syntax and implement proper property-based tests
